### ISSUE TITLE
HTML shown as text

### ISSUE THREAD

**Issue by i10111pn** [RSmetanyuk/Football-statistic-app#11]
**Steps to reproduce:**
1. Click on `Teams` link.
2. Click on any team.
3. Note that server send you response which contains HTML
 
![image](https://user-images.githubusercontent.com/11459051/31055706-b2f78a48-a6cf-11e7-96c1-e0c6519104d4.png)

**Expected behavior:**
Applications render this part with HTML.

**Current behavior:**
HTML is shown as text.
![image](https://user-images.githubusercontent.com/11459051/31055716-dd09b75c-a6cf-11e7-988e-1cb23ff5262a.png)

**Comment by i10111pn** [comment]
To solve this problem see:
https://stackoverflow.com/questions/9381926/insert-html-into-view

**Comment by RSmetanyuk** [comment]
Done

**Comment by i10111pn** [comment]
Align all details info to the left

**Comment by RSmetanyuk** [comment]
Done
