### ISSUE TITLE
Add ability to navigate from match to championship 

### ISSUE THREAD

**Issue by i10111pn** [RSmetanyuk/Football-statistic-app#13]
Example, this should be a link to a championship.

![image](https://user-images.githubusercontent.com/11459051/31055892-89d47b46-a6d2-11e7-8f19-7fbf376a46b3.png)

**Comment by RSmetanyuk** [comment]
The server does not give championship id, it only gives title "Єврокубки, Ліга Чемпіонів" so it will be more difficult.

**Comment by RSmetanyuk** [comment]
Done with links for teams

**Comment by i10111pn** [comment]
Could you find `championship id` by championship name?

**Comment by RSmetanyuk** [comment]
Done

**Comment by i10111pn** [comment]
What happening with URL after clicking on championship from a match?

https://football-statistic-app.herokuapp.com/index.html#!/championships/%D0%84%D0%B2%D1%80%D0%BE%D0%BA%D1%83%D0%B1%D0%BA%D0%B8,%20%D0%9B%D1%96%D0%B3%D0%B0%20%D0%A7%D0%B5%D0%BC%D0%BF%D1%96%D0%BE%D0%BD%D1%96%D0%B2

**Comment by RSmetanyuk** [comment]
Local here is 
http://127.0.0.1:8080/#!/championships/Єврокубки, Ліга Чемпіонів

**Comment by i10111pn** [comment]
Why is not id?
And how it working?
Did you add the ability to route by name?

**Comment by RSmetanyuk** [comment]
Routes by name instead id.
Championships.controler.js finds id and shows correct page.

**Comment by i10111pn** [comment]
What code is responsible for it?

**Comment by RSmetanyuk** [comment]
Code here:
![default](https://user-images.githubusercontent.com/29253760/31085673-7ea0314c-a7a0-11e7-93ac-12524fbcc8a3.png)
I can change code to routing only by ID.

**Comment by i10111pn** [comment]
Could show id in URL instead of name in this case?

**Comment by RSmetanyuk** [comment]
In this case you a going from matches by link href="#!championships/Єврокубки, Ліга Чемпіонів"

**Comment by RSmetanyuk** [comment]
I can rework app that you will be going by link href="#!championships/2"

**Comment by i10111pn** [comment]
Rework it to show `id` in URL.

**Comment by RSmetanyuk** [comment]
Done
