### ISSUE TITLE
Empty pagination's result page 

### ISSUE THREAD

**Issue by i10111pn** [RSmetanyuk/Football-statistic-app#16]
**Steps to reproduce:**
1. Go to `Teams`
2. Enter `Ки` In search input
3. Сlick on page 3
 
**Expected behavior:**
Some results are showed

**Current behavior:**
Page is empty

![image](https://user-images.githubusercontent.com/11459051/31057938-ed213678-a6f3-11e7-98f5-e73a3f70a4a6.png)

**Comment by RSmetanyuk** [comment]
Done
