### ISSUE TITLE
Incorrect link highlighting 

### ISSUE THREAD

**Issue by i10111pn** [RSmetanyuk/Football-statistic-app#17]
**Steps to reproduce:**
1. Go to `Matches`
2. Link in browser is https://football-statistic-app.herokuapp.com/index.html#!/teams
3. Delete `!/teams` from URL and press Enter (do not delete `#`)
4. Now you are at default route (Championships)

**Expected behavior:**
`Championships` link is highlighted

**Current behavior:**
`Matches` link is highlighted

![image](https://user-images.githubusercontent.com/11459051/31058251-6b57b0e4-a6f9-11e7-9f15-c4d383e40692.png)

**Comment by RSmetanyuk** [comment]
Done. This problem has been solved after the replacement menu-bar
