### ISSUE TITLE
Rework search

### ISSUE THREAD

**Issue by i10111pn** [RSmetanyuk/Football-statistic-app#20]
Example for `Championships`

This is the initial state of `championships` page:
![image](https://user-images.githubusercontent.com/11459051/31086487-9bb653b8-a7a2-11e7-8837-0108b4a57a8a.png)

After click on 'championships' text page should look like this:
![image](https://user-images.githubusercontent.com/11459051/31086795-84f87402-a7a3-11e7-8db5-47a8c92574a9.png)

Do the same for `Teams` and `Matches`

**Comment by RSmetanyuk** [comment]
Done

**Comment by i10111pn** [comment]
Hide search input when a user clicked outside and did not type anything in search input.

**Comment by i10111pn** [comment]
Also, you should not do DOM manipulations in your code:

```
Data.hideById = function(hideByIdName, unhideByIdName) {
  document.getElementById(hideByIdName).className = "hidden";
   document.getElementById(unhideByIdName).removeAttribute("class")
};
```
Rework it with `ng-class`.

**Comment by i10111pn** [comment]
Make search input full width:

![image](https://user-images.githubusercontent.com/11459051/31280251-70d28418-aab4-11e7-9a59-3c30e8feec6d.png)

**Comment by RSmetanyuk** [comment]
May I use glyphicons-remove-circle istead of hiding search input when a user clicked outside and did not type anything in search input?

**Comment by i10111pn** [comment]
Yes

**Comment by RSmetanyuk** [comment]
Done
