### ISSUE TITLE
Fetch API data once

### ISSUE THREAD

**Issue by i10111pn** [RSmetanyuk/Football-statistic-app#21]
The application sends a new request every time when you navigate between pages.

Example:
Navigate in this order 
```
championships
teams
championships
matches

```
In this case, you should send request for `championships` once
But now it is sending request twice:
![image](https://user-images.githubusercontent.com/11459051/31087286-2070aa20-a7a5-11e7-8474-0d89e3732f67.png)

Try to cache results.

**Comment by RSmetanyuk** [comment]
Pictures from server I also should get once for each picture?

**Comment by i10111pn** [comment]
I don't know. Is it possible? If yes - do it.

**Comment by RSmetanyuk** [comment]
Done
