### ISSUE TITLE
App enhancements

### ISSUE THREAD

**Issue by i10111pn** [RSmetanyuk/Football-statistic-app#22]
1. Align content to the left on `championship` page:
![image](https://user-images.githubusercontent.com/11459051/31087564-29e9a93e-a7a6-11e7-85cc-9b333be2c72b.png)

2. For `team` page:
remove team id
championship id should be a link with the name 'Деталі чемпіонату'
all properties names should be bold text
![image](https://user-images.githubusercontent.com/11459051/31087793-12a45e44-a7a7-11e7-81f6-ba389cc8b9cb.png)

**Comment by RSmetanyuk** [comment]
Done

**Comment by RSmetanyuk** [comment]
Done
