### ISSUE TITLE
Add loading spinner while app waiting for  response

### ISSUE THREAD

**Issue by i10111pn** [RSmetanyuk/Football-statistic-app#23]
When the application is waiting for response user see:

![image](https://user-images.githubusercontent.com/11459051/31126370-4356371c-a854-11e7-9dae-5150665be78f.png)

-------------------------------------------------------------

![image](https://user-images.githubusercontent.com/11459051/31126380-4a8f7a2a-a854-11e7-83c9-ce0515398bd1.png)

Add loading spinner while response data is not ready:

![image](https://user-images.githubusercontent.com/11459051/31126692-2de037a6-a855-11e7-963d-1254bc4f5afa.png)

-------------------------------------------------------------

![image](https://user-images.githubusercontent.com/11459051/31126700-337655a6-a855-11e7-95fe-9eb4bc6a08c0.png)

Do the same for `Championships`.
See example of spinner here http://plnkr.co/edit/PUjrEIt0YLTwr0rUInv8?p=preview

**Comment by RSmetanyuk** [comment]
Done. It works local, but I dont see spinner on heroku

**Comment by i10111pn** [comment]
Open console, you have errors on Heroku:

![image](https://user-images.githubusercontent.com/11459051/31279530-0c352de6-aab2-11e7-97f7-056ee02044db.png)

**Comment by RSmetanyuk** [comment]
Done

**Comment by i10111pn** [comment]
Hide all content in the main block and display spinner in the center there:

![image](https://user-images.githubusercontent.com/11459051/31294797-f2807918-aae4-11e7-95f9-ce8c63e9f1a8.png)

**Comment by RSmetanyuk** [comment]
Done

**Comment by i10111pn** [comment]
Add `min-height` to main container and display spinner in the center there:

![image](https://user-images.githubusercontent.com/11459051/31352886-1a929002-ad39-11e7-978d-79ce3f94eac2.png)

**Comment by RSmetanyuk** [comment]
Done
