### ISSUE TITLE
Add eslint to your app

### ISSUE THREAD

**Issue by i10111pn** [RSmetanyuk/Football-statistic-app#25]
Add linter to your app.
Follow this instructions:

**1.** Run in cmd: 
`npm install --save-dev eslint`
`npm install -g eslint`

**2.** Run in cmd: `eslint --init`
Answer in this order:
**Inspect your JavaScript file(s)**
Files path  `js/*.js`
Format -  **json**
**No** for ES6
Run in **Browser**
**No** for CommonJS
**No** for JSX

**3.** To check if eslint works run this command in cmd:
`eslint js/match.controller.js`

**4.**  Run in cmd: `npm install --save-dev eslint-plugin-angular`

**5.** Use the shareable config by adding it to your `.eslintrc`:
“extends”: “plugin:angular/johnpapa”

**6.** Manually  add plugins section:
```
{
    "plugins": [
        "angular"
    ],
    "rules": {
     …
}
```

**7.** Run in cmd:  `npm install -g eslint-plugin-angular`

Now your config is ready, just run `eslint js/*.js`
Try to fix all gotten errors/warnings.

**Comment by i10111pn** [comment]
Do `Usage with shareable config`

**Comment by i10111pn** [comment]
Create `.eslintrc` file from this skeleton:
https://gist.github.com/jhartikainen/7dd4124631fcff66b43f

**Comment by i10111pn** [comment]
Also install eslint globally, run this command:

`npm install -g jshint`

**Comment by RSmetanyuk** [comment]
Done

**Comment by RSmetanyuk** [comment]
Done. Fixed 13 errors with eslint.

**Comment by RSmetanyuk** [comment]
Done
