### ISSUE TITLE
Format your code

### ISSUE THREAD

**Issue by i10111pn** [RSmetanyuk/Football-statistic-app#26]
**1.** CSS class names should be in named in format "word1-word2"
Example:
![image](https://user-images.githubusercontent.com/11459051/31127155-b5fed100-a856-11e7-9001-bda5b3ffbdb5.png)
this classes names should be renamed to `.table-matches` `.table-teams` `table-championships`

**2.** Use the same files' name convention.

![image](https://user-images.githubusercontent.com/11459051/31129905-91b7b4ee-a85e-11e7-934f-96785d3e9bf4.png)

Rename `headerController.js`:

**3.** Why do you copy lib code to `dirPagination.js` can't you just use it from node modules?

**4.** `championships.template.html` 
format too long lines 
`<img src="https://footballbet.com.ua/table/embl/{{country.title}}.jpg" height="35" width="35" /><a href="#!championships/{{country.id_championship}}">  {{country.name}}</span></a>`

**5.** `matches.detail.template.html`
format too long lines
```
<td><a href="#!championships/{{Data.matches[idMatch].title}}">{{Data.matches[idMatch].title}}  </a></td>
<td><a href="#!teams/{{Data.matches[idMatch].idFirstTeam}}">{{Data.matches[idMatch].firstTeam}} </a>{{Data.matches[idMatch].firstTeamGoal}}:{{Data.matches[idMatch].secondTeamGoal}} <a href="#!teams/{{Data.matches[idMatch].idSecondTeam}}">{{Data.matches[idMatch].secondTeam}}</a></td>
```

**Comment by RSmetanyuk** [comment]
1. Done
2. Done
3. I have no find link for this plugin
4. Done
5. Done
How about names of template files?

**Comment by i10111pn** [comment]
Rename details templates.
Example:
`championships.detail.template.html` to `championship.template.html`

**Comment by i10111pn** [comment]
Rename details controllers.
Example:
`championship-details-controler.js` to `championship.controler.js`

**Comment by i10111pn** [comment]
Rename `data-factory.js` to `data.factory.js`

**Comment by i10111pn** [comment]
Remove commented styles in `style.css` or add a description why do you need it.

**Comment by i10111pn** [comment]
In `js` folder create a new folder named `libs` and move all not your own code to this folder.

**Comment by i10111pn** [comment]
Remove `angular-loading-spinner.js` and use `angular-spinner.min.js`

**Comment by i10111pn** [comment]
Check if you need ` jquery.min.js`. If not - remove it.

**Comment by i10111pn** [comment]
Check which one are you using and leave only one:
```
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/spin.js/2.3.2/spin.min.js">
<script type="text/javascript" src="js/angular-spinner.min.js">
<script type="text/javascript" src="js/angular-loading-spinner.js">
```

**Comment by i10111pn** [comment]
Format too long lines in templates:
`championships.template.html` line 22
`matches.detail.template.html` line 16
`teams.detail.template.html` line 18

**Comment by i10111pn** [comment]
Fix typo in file name `matche.template.html`

**Comment by i10111pn** [comment]
Delete `angular-loading-spinner.js` and move `angular-spinner.min.js` to `libs` folder.

**Comment by i10111pn** [comment]
Are you using 
`<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/spin.js/2.3.2/spin.min.js">`?

or local `angular-loading-spinner`?

**Comment by RSmetanyuk** [comment]
I use src="https://cdnjs.cloudflare.com/ajax/libs/spin.js/2.3.2/spin.min.js

**Comment by RSmetanyuk** [comment]
I may also delete
  link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css"

**Comment by i10111pn** [comment]
Delete `bootstrap-theme.min.css` if you are not using it.
And delete both `angular-loading-spinner.js` and `angular-spinner.min.js`

**Comment by RSmetanyuk** [comment]
Done
