### ISSUE TITLE
Team details are not shown

### ISSUE THREAD

**Issue by i10111pn** [RSmetanyuk/Football-statistic-app#28]
**Steps to reproduce (v1):**
1. Click on link to team https://football-statistic-app.herokuapp.com/index.html#!/teams/86 

**Steps to reproduce (v2):**
1. Go to `Teams`
2. Click on any team
3. Team details are shown
4. Press F5 button

**Expected behavior:**
Team details are shown

**Current behavior:**
Team details are not shown

![image](https://user-images.githubusercontent.com/11459051/31179183-e5671f4c-a923-11e7-9a09-103631701e85.png)

**Comment by i10111pn** [comment]
The same for `Matches`

**Comment by RSmetanyuk** [comment]
Done
