### ISSUE TITLE
Move links to the header

### ISSUE THREAD

**Issue by i10111pn** [RSmetanyuk/Football-statistic-app#5]
Move this links:
```
Championships
Teams
Matches
```
to the header.

Also, add `About` link.
By clicking on this link show short description of this project.

**Comment by RSmetanyuk** [comment]
Done

**Comment by i10111pn** [comment]
Remove this text:

![image](https://user-images.githubusercontent.com/11459051/30964944-1f19eb6a-a45c-11e7-83ae-f23bc931d157.png)

**Comment by i10111pn** [comment]
The header should look like this:
![image](https://user-images.githubusercontent.com/11459051/30965019-70749d3e-a45c-11e7-85bc-d1e1a25b5451.png)

**Comment by RSmetanyuk** [comment]
Done
