### ISSUE TITLE
Add details

### ISSUE THREAD

**Issue by i10111pn** [RSmetanyuk/Football-statistic-app#7]
Show details of 
```
Championships
Teams
Matches
```
by clicking on a list's item.

**Comment by i10111pn** [comment]
Championship details:

![image](https://user-images.githubusercontent.com/11459051/30967351-b383bd6e-a464-11e7-9c5f-9380c442c473.png)

**Comment by i10111pn** [comment]
Team details:

![image](https://user-images.githubusercontent.com/11459051/30967402-ded0c8fe-a464-11e7-8d66-fbc1db89aee2.png)

**Comment by i10111pn** [comment]
For matches just show list
teamA - teamB
teamC - teamD
teamE - teamF
...

And on click on a match -  show details like you are showing now:
![image](https://user-images.githubusercontent.com/11459051/30967550-53f017de-a465-11e7-83b2-1b5dbb2c86f5.png)

**Comment by RSmetanyuk** [comment]
Details should show in additional box or instead current view?

**Comment by RSmetanyuk** [comment]
Done, but bugs present

**Comment by i10111pn** [comment]
Describe this bug in comment here

**Comment by RSmetanyuk** [comment]
1. In second and next teams list, details view does not show correct team.

**Comment by RSmetanyuk** [comment]
2. 
![bug](https://user-images.githubusercontent.com/29253760/31052339-77afa7da-a68a-11e7-866b-41146bfcb136.png)

**Comment by RSmetanyuk** [comment]
I have no idea how to fix #2 bug
