### ISSUE TITLE
Logo is absent 

### ISSUE THREAD

**Issue by i10111pn** [RSmetanyuk/Football-statistic-app#8]
![image](https://user-images.githubusercontent.com/11459051/30965088-bb33a572-a45c-11e7-94e5-55c6d0c01c8d.png)

![image](https://user-images.githubusercontent.com/11459051/30965097-c6589b1a-a45c-11e7-90de-771cd49b6f9f.png)

**Comment by RSmetanyuk** [comment]
Done
