### ISSUE TITLE
Add active link highlighting   

### ISSUE THREAD

**Issue by i10111pn** [RSmetanyuk/Football-statistic-app#9]
Use ui-router https://stackoverflow.com/questions/22219315/angular-ui-router-ui-sref-active-and-nested-states

For CSS steles see example here:
https://getbootstrap.com/docs/3.3/components/#navbar

**Comment by RSmetanyuk** [comment]
Done in an easier way, through classes and ng-click

**Comment by RSmetanyuk** [comment]
Done

**Comment by i10111pn** [comment]
Do highlighting more visible. See example here:
https://getbootstrap.com/docs/3.3/components/#navbar

Highlight the whole link container.

**Comment by RSmetanyuk** [comment]
Done
